### ISSUE TITLE
Template Cover error

### ISSUE THREAD

**Issue by tatunts** [home-assistant/homebridge-homeassistant#221]
Hello everyone!

I have a couple of template covers set up that are unable to work. Here is the error from log:

```
2017-09-13 13:05:32 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 179, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/site-packages/homeassistant/core.py", line 1025, in _event_to_service_call
    yield from service_handler.func(service_call)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/cover/__init__.py", line 173, in async_handle_cover_service
    yield from getattr(cover, method['method'])(**params)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/cover/template.py", line 297, in async_set_cover_position
    yield from self._position_script.async_run(
AttributeError: 'NoneType' object has no attribute 'async_run'
```

When acrivated from Homebridge (Home app) I get this error. The state is changed but no command is sent (script). I am using it with optimistic mode on to set the state (working great with HA UI)

Here is my configuration:
```
cover:
  - platform: template
    covers:
      persiana_suite:
        optimistic: true
        friendly_name: "Persiana da suíte"
        open_cover:
          service: script.persiana_suite_abrir
          entity_id: script.persiana_suite_abrir
        close_cover:
          service: script.persiana_suite_fechar
          entity_id: script.persiana_suite_fechar
        stop_cover:
          service: script.persiana_suite_parar
          entity_id: script.persiana_suite_parar
```
After update to 0.53 it started to work but after a Hass.io restart, it broke again...

Can someone help me?

Thanks a lot!

**Comment by tatunts** [comment]
Hello! I’ve managed to fix that by changing the template cover behavior:

```
  persiana_sala:
    optimistic: true
    set_cover_position:
      service_template: >
        {% if is_state('cover.persiana_sala', 'open') %}
          script.persiana_sala_fechar
        {% elif is_state('cover.persiana_sala', 'closed') %}
          script.persiana_sala_abrir
        {% endif %}
```

Now using the set_cover_position: homebridge seems to communicate with HA the right way!

Thanks!
